# Generated by Django 5.1.1 on 2024-10-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("title_en", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=10)),
                ("img_src", models.CharField(max_length=100)),
                ("release_date", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=20)),
                ("director", models.CharField(max_length=40)),
                ("cast", models.CharField(max_length=100)),
                ("assignment", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "db_movie",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acc", models.CharField(max_length=20, unique=True)),
                ("pwd", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=20)),
                ("registerdate", models.DateTimeField()),
                ("tel", models.CharField(max_length=10)),
                ("profile_pic", models.ImageField(upload_to="static/images")),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomType", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("playTime", models.CharField(max_length=20)),
                ("theater_name", models.CharField(max_length=40)),
                ("place", models.CharField(max_length=40)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theater_movie",
                        to="movie_ticket_booking.movie",
                    ),
                ),
            ],
            options={
                "db_table": "db_show",
            },
        ),
    ]
