# Generated by Django 5.1.1 on 2024-10-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_ticket_booking", "0002_alter_show_date_alter_show_playtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="show",
            name="date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="show",
            name="playTime",
            field=models.CharField(max_length=20),
        ),
    ]
