# Generated by Django 5.1.1 on 2024-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movie_ticket_booking",
            "0003_alter_movie_release_date_alter_show_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="level",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
