# Generated by Django 5.1.1 on 2024-10-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_ticket_booking", "0004_movie_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tb_user", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=500)),
                ("comment_time", models.DateTimeField()),
                (
                    "tb_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_movie",
                        to="movie_ticket_booking.movie",
                    ),
                ),
            ],
            options={
                "db_table": "db_comment",
            },
        ),
    ]
