# Generated by Django 5.1.1 on 2024-10-15 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_ticket_booking", "0005_textboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("click_time", models.DateTimeField()),
                (
                    "fav_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fav_movie_id",
                        to="movie_ticket_booking.movie",
                    ),
                ),
                (
                    "fav_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fav_user_id",
                        to="movie_ticket_booking.user",
                    ),
                ),
            ],
            options={
                "db_table": "db_favorite",
            },
        ),
    ]
