# Generated by Django 5.1.1 on 2024-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_ticket_booking", "0007_theater"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="date",
            field=models.DateField(),
        ),
    ]
