# Generated by Django 5.1.1 on 2024-10-23 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_ticket_booking", "0010_user_verify_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
    ]
