# Generated by Django 5.1.1 on 2024-10-24 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_ticket_booking", "0011_remove_user_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verify_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verify_state",
        ),
    ]
