# Generated by Django 5.1.1 on 2024-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movie_ticket_booking",
            "0012_remove_user_verify_code_remove_user_verify_state",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_id",
            field=models.BooleanField(default=False),
        ),
    ]
